#!/bin/bash

USAGE="<search> : search for a branch with grep"

. "$(git --exec-path)/git-sh-setup"

require_work_tree

TARGET="$1"

if [ "$TARGET" != "" ]; then
   cd_to_toplevel
   git b | grep "$TARGET"
else
   usage
fi
