#!/bin/bash

. "$(git --exec-path)/git-sh-setup"

require_clean_work_tree sync "Please commit or stash all your changes."

require_work_tree
cd_to_toplevel
git fetch origin
git checkout master
git pull origin master
git push origin master
