#!/bin/bash

. "$(git --exec-path)/git-sh-setup"

require_clean_work_tree sync "Please commit or stash all your changes."

TARGET="$1"

if [ "$TARGET" != "" ]; then
    require_work_tree
    cd_to_toplevel
    git fetch origin
    git checkout $TARGET
    git pull origin $TARGET
fi
