#!/bin/bash

USAGE="<target> : hard delete branch <target>"

. "$(git --exec-path)/git-sh-setup"

require_work_tree
require_clean_work_tree new "Please commit or stash all your changes."

TARGET="$1"

if [ "$TARGET" != "" ] && [ "$TARGET" != "master" ] && [ "$TARGET" != "qa" ]; then
   cd_to_toplevel
   git checkout master
   git branch -D "$TARGET"
else
   usage
fi
