#!/bin/bash

. "$(git --exec-path)/git-sh-setup"

require_clean_work_tree sync "Please commit or stash all your changes."

CURRENT="$(git branch | grep '*' | awk '{print $2}')"

if [ "$CURRENT" != "" ]; then
  require_work_tree
  cd_to_toplevel
  git fetch origin
  git pull origin $CURRENT
  git push origin $CURRENT
fi
